server:
  servlet:
    context-path: /vuce-zee-api-contrato
  port : 8081
# ===============================
# = DATA SOURCE POSTGRESQL
# ===============================

#configuracion postgresql basica

spring:
  datasource:
    #url: jdbc:postgresql://10.19.34.188/zee_db
    url: jdbc:postgresql://10.19.34.188/zee_db?currentSchema=vuce_zee
    username: zeeperu
    password: CicQB888PD8LJGxn
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        # Hibernate ddl auto (create, create-drop, validate, update, none)
        ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #logging:
  #  pattern:
  #    level: '%5p %mdc'
  #  level:
  #    pe.gob.vuce: INFO
  #    org.springframework: DEBUG
  #    org.springframework.data: TRACE

  #configuracion maximo tamanio peso de subida de archivos
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  services:
      maestroUrl: 'https://landing-desa.vuce.gob.pe/vuce-zee-api-lote/'
app:
  contrato-etapas:
    1: 'Formulario principal'
    2: 'Lotes'